module.exports = {
  plugins: ["vitest"],
  overrides: [
    {
      files: ["**/*.{test,spec}.{js,jsx,ts,tsx}"],
      rules: {
        "vitest/expect-expect": "error",
        "vitest/consistent-test-it": "off",
        "vitest/max-expects": "off",
        "vitest/max-nested-describe": "off",
        "vitest/no-alias-method": "off",
        "vitest/no-commented-out-tests": "warn",
        "vitest/no-conditional-expect": "error",
        "vitest/no-conditional-in-test": "error",
        "vitest/no-conditional-tests": "error",
        "vitest/no-disabled-tests": "warn",
        "vitest/no-done-callback": "warn",
        "vitest/no-duplicate-hooks": "error",
        "vitest/no-focused-tests": "warn",
        "vitest/no-hooks": "off",
        "vitest/no-identical-title": "error",
        "vitest/no-interpolation-in-snapshots": "off",
        "vitest/no-large-snapshots": "off",
        "vitest/no-mocks-import": "error",
        "vitest/no-restricted-matchers": "off",
        "vitest/no-restricted-vi-methods": "off",
        "vitest/no-standalone-expect": "error",
        "vitest/no-test-prefixes": "error",
        "vitest/no-test-return-statement": "error",
        "vitest/prefer-called-with": "error",
        "vitest/prefer-comparison-matcher": "error",
        "vitest/prefer-each": "error",
        "vitest/prefer-equality-matcher": "error",
        "vitest/prefer-expect-resolves": "error",
        "vitest/prefer-hooks-in-order": "error",
        "vitest/prefer-hooks-on-top": "error",
        "vitest/prefer-lowercase-title": "error",
        "vitest/prefer-mock-promise-shorthand": "error",
        "vitest/prefer-snapshot-hint": "error",
        "vitest/prefer-spy-on": "error",
        "vitest/prefer-strict-equal": "error",
        "vitest/prefer-to-be": "error",
        "vitest/prefer-to-be-falsy": "error",
        "vitest/prefer-to-be-object": "error",
        "vitest/prefer-to-be-truthy": "error",
        "vitest/prefer-to-contain": "error",
        "vitest/prefer-to-have-length": "error",
        "vitest/prefer-todo": "error",
        "vitest/require-hook": "off",
        "vitest/require-to-throw-message": "off",
        "vitest/require-top-level-describe": "off",
        "vitest/valid-describe-callback": "error",
        "vitest/valid-expect": "error",
        "vitest/valid-title": "error",
      },
    },
  ],
};
